# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solveur Slitherlink (Squelette de Phase 3)
#' @param h_edges Matrice segments horizontaux
#' @param v_edges Matrice segments verticaux
#' @param indices Matrice des chiffres contraintes
#' @export
solve_slitherlink_cpp <- function(h_edges, v_edges, indices) {
    .Call(`_SlitherlinkR_solve_slitherlink_cpp`, h_edges, v_edges, indices)
}

#' Verifier la connexion Rcpp
#' @export
check_cpp_connection <- function() {
    .Call(`_SlitherlinkR_check_cpp_connection`)
}

